### ISSUE TITLE
[Bug] Requesting changes to 'Create an Access Profile' (create-access-profile)

### ISSUE THREAD

**Issue by calebstromgren** [sailpoint-oss/developer.sailpoint.com#101]
The example request body contains items that you would not include in the request to create an access profile, such as id, created, modified

**Comment by colin-mckibben-sp** [comment]
This is a bug with the docusaurus API spec renderer.  I opened a bug report with them.  https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/347

**Comment by colin-mckibben-sp** [comment]
The docusaurus bug has been fixed, and the `created`, `modified`, and `id` fields no longer appear in the request body.
