### ISSUE TITLE
[Bug] Boolean default values aren't always explicitly specified

### ISSUE THREAD

**Issue by james-haytko-sp** [sailpoint-oss/developer.sailpoint.com#108]
**Describe the bug** 
Boolean default values aren't always explicitly specified in the developer and API docs. Generally, when they aren't specified, the default value is implied to be false, but that's not always clear based on the context. 
We can either make the default value explicit and obvious for all the booleans in the docs, or we can specify a rule that if the default value isn't specified, it's false (it seems like this is generally the case, but I'm not sure whether it's always the case). 

Sometimes, the booleans have an explicit default value of 'false.' 
Example: [Create Role](https://developer.sailpoint.com/idn/api/beta/create-role)
![createroledefaultfalse](https://user-images.githubusercontent.com/101364748/201427392-74d7f547-14ec-4d84-b47d-dd748bf87494.png)

Often, the booleans have an implicit default value of 'false.' 
Example: [Create a campaign](https://developer.sailpoint.com/idn/api/beta/create-campaign)
![createcampaigndefaultimplicitlyfalse](https://user-images.githubusercontent.com/101364748/201429604-f2319f39-43ae-4b7b-8ad5-d1b46ead6a02.png)

Sometimes the booleans have an unclear default value based on the context. 
Example: [Create Access Profile](https://developer.sailpoint.com/idn/api/beta/create-access-profile)
![createaccessprofiledefaultunclear](https://user-images.githubusercontent.com/101364748/201427376-2bc8b907-ccdf-43fa-8da7-08bc4707c0d3.png)
The 'requestable' boolean sounds like it could be true here, based on the context, but it could still be false.

**Comment by colin-mckibben-sp** [comment]
There is a new linter rule that enforces default values for booleans.  This will be fixed over time.

https://github.com/sailpoint-oss/api-linter/blob/16250828c86a94af7ec7c9f4418f5fda9ea9f534/schema-ruleset.yaml#L38
