### ISSUE TITLE
[Feature] Better documentation on input limitations for API calls

### ISSUE THREAD

**Issue by jordan-violet-sp** [sailpoint-oss/developer.sailpoint.com#112]
See: https://developer.sailpoint.com/discuss/t/idn-name-limits-and-restrictions/6778

**Comment by colin-mckibben-sp** [comment]
The quickest way to find these limits will probably be to write a script that tests the length and special character limits of every field on every API.  This will likely be something we can look at after Developer Days.

**Comment by colin-mckibben-sp** [comment]
We don't have the bandwidth to work on this in the near future.

**Comment by jordan-violet-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/idn-name-limits-and-restrictions/6778/2
