### ISSUE TITLE
add information on how to compute the field encryptedPassword  for 'Set Identity's Password' (set-password)

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/developer.sailpoint.com#115]
At this moment, there is no information on how to compute the field `encryptedPassword  `of the payload for `set-password`.
There might be some example on how to compute this with openssl for instance, a widely used tool.

For instance, on Linux: 
```
echo -n "SuperStrongP@ssw0rd" |  openssl rsautl -encrypt -pubin -inkey pub.pem  | base64 -w 0
```
`echo -n` to prevent a newline at the end.
`base64 -w 0` to have no wrapping.
pub.pem is the public key returns by the `query-password-info` endpoint.

**Comment by colin-mckibben-sp** [comment]
Another user reported having to wrap the key with  

-----BEGIN PUBLIC KEY-----
-----END PUBLIC KEY-----

to get openssl to take it.

**Comment by jordan-violet-sp** [comment]
Fixed in docs now: https://developer.sailpoint.com/idn/api/v3/set-password
