### ISSUE TITLE
[Bug] Example data on /api/v3/scheduled-search-create/ incorrect

### ISSUE THREAD

**Issue by jason545454** [sailpoint-oss/developer.sailpoint.com#120]
The Months on the example data on https://developer.sailpoint.com/idn/api/v3/scheduled-search-create/ is not correct. It has days instead of months.

```
"schedule": {
    "type": "WEEKLY",
    "months": {
      "type": "LIST",
      "values": [
        "MON",
        "WED"
      ],
```

**Comment by colin-mckibben-sp** [comment]
@jason545454 thank you for reporting this.  The scheduled search spec had some other inconsistencies, in addition to incorrect examples, that we fixed.  Please see the new spec that provides additional examples for each schedule type. https://developer.sailpoint.com/idn/api/v3/scheduled-search-create
