### ISSUE TITLE
[Feature] Pagination on Standard Collection Parameters

### ISSUE THREAD

**Issue by calebstromgren** [sailpoint-oss/developer.sailpoint.com#128]
The documentation at https://developer.sailpoint.com/idn/api/standard-collection-parameters#paginating-results works for paging but only up to 10,000 records, and does not call out the limit.  I would recommend updating the documentation to include that as well as the details (or a link to) of this discussion post so folks can get past it.  I was about to create a new post until i stumbled upon it.  (kudos to the recommendations that showed up while i was typing my post)

https://developer.sailpoint.com/discuss/t/v3-search-api-offset/614/4

**Comment by colin-mckibben-sp** [comment]
Thanks Caleb.  I just had the thought yesterday that our pagination docs don't mention the 10,000 limit for the search API.

@james-haytko-sp this is in relation to DEVREL-804.  You'll want to update your progress on this documentation here so our community is aware of it.

**Comment by james-haytko-sp** [comment]
We've updated the documentation to include details about how to use searchafter to page records past the 10k limit: https://developer.sailpoint.com/idn/api/standard-collection-parameters/#paginating-search-queries
