### ISSUE TITLE
[Feature] Encourage version control in SaaS Connectivity docs

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#131]
Per this forum post: https://developer.sailpoint.com/discuss/t/saas-connector-recovery/7400/2

Since connector source code is not recoverable from IDN, we need to update the connector docs to make this fact known and to encourage users to use version control or regular backups to avoid data loss.

**Comment by james-haytko-sp** [comment]
I added an advisory note recommending that users use version control or backups to the saas connectivity docs: https://developer.sailpoint.com/idn/docs/saas-connectivity/.
