### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Perform Search' (search-post)

### ISSUE THREAD

**Issue by identiquest** [sailpoint-oss/developer.sailpoint.com#147]
The curl example for Perform Search has a bug.  Your "sort" example has an extra set of []
"sort": [
    [
      "displayName",
      "+id"
    ]
  ]

should be
"sort": [
      "displayName",
      "+id"
    ]

**Comment by identiquest** [comment]
same for searchAfter
,
  "searchAfter": [
    [
      "John Doe",
      "2c91808375d8e80a0175e1f88a575221"
    ]
  ]

**Comment by james-haytko-sp** [comment]
Thanks for catching this! This is fixed now. https://developer.sailpoint.com/idn/api/v3/search-post
