### ISSUE TITLE
[Feature] Make links in documentation a different color so they are more visible

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#153]
**Is your feature request related to a problem? Please describe.** 

Links in the documentation have a very similar color to the surrounding text, making it hard to see that there are links in the documentation.

For example, here is the search collection documentation: https://developer.sailpoint.com/idn/api/v3/search

![image](https://user-images.githubusercontent.com/75683148/214611221-1b9802c9-51c7-4747-977c-39e369ff139a.png)

There is actually a link in this document, which you can see here after hovering over it.

![image](https://user-images.githubusercontent.com/75683148/214611394-571e6d02-3a6a-4018-be00-4bfdb75a263c.png)

This also affects technical docs, not just API collection docs.  Here is the event trigger filter docs. https://developer.sailpoint.com/idn/docs/event-triggers/filtering-events#developing-filters

![image](https://user-images.githubusercontent.com/75683148/214612165-718b82ff-1c33-4214-811a-fc0c9b2080a2.png)

And here is the link that is hidden:

![image](https://user-images.githubusercontent.com/75683148/214612249-ccede931-4bd3-4471-a99e-0de58534f7a3.png)

**Describe the solution you'd like.**

Make the link text a different color so it is easier to spot.

**Describe alternatives you've considered.** A clear and concise description of any alternative solutions or features you've considered. Ex. I have seen similar features on [...]

**Additional context** Add any other context or screenshots about the feature request here.

Dark and light mode both exhibit this issue.

**Comment by jordan-violet-sp** [comment]
@luke-hagar-sp this seems to break with the Tailwind css that was added to custom.css. I'll let you fix it so I don't break any tailwind items you may have used elsewhere.

**Comment by colin-mckibben-sp** [comment]
fixed in #154
