### ISSUE TITLE
[Bug] Missing Link in Connector Spec Doc

### ISSUE THREAD

**Issue by mattsuid** [sailpoint-oss/developer.sailpoint.com#161]
**Describe the bug** 

A link is missing in the connector-spec documentation for SaaS connectors.

**To Reproduce** 

You can see the missing link @ https://developer.sailpoint.com/idn/docs/saas-connectivity/connector-spec and in source @ https://github.com/sailpoint-oss/developer.sailpoint.com/blob/main/products/idn/docs/identity-now/saas-connectivity/connector-spec.md

The line documenting the commands says you can find a link "here" but the link is missing.

**Expected behavior**

Link would be present on the word "here".

**Actual behavior** 

Link is not present on the word "here"

**Screenshots**

![Screenshot 2023-02-01 at 12 26 53 PM](https://user-images.githubusercontent.com/17863645/216130352-2c1e0d38-5a86-4c35-a914-14516e8c10b0.png)

**Browser (please complete the following information):**

- Browser: [all]

**Additional context** 

N/A

**Comment by colin-mckibben-sp** [comment]
This has been fixed.  It is being deployed as we speak. You should see the link soon.
