### ISSUE TITLE
[Feature] Update all copy on developer.sailpoint.com to sentence case from all other cases, where applicable

### ISSUE THREAD

**Issue by jordan-violet-sp** [sailpoint-oss/developer.sailpoint.com#171]
The marketing brand team has chosen for SailPoint to switch all copy from all other cases to sentence case. This includes titles, buttons, description, etc.

Example of title case:
"Get Started with IdentityNow"

Same example with sentence case:
"Get started with IdentityNow"

**Comment by colin-mckibben-sp** [comment]
@jordan-violet-sp is this still relevant?
