### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Create SOD policy' (create-sod-policy)

### ISSUE THREAD

**Issue by lori-vangulick-sp** [sailpoint-oss/developer.sailpoint.com#214]
**Describe the bug** A clear and concise description of what the bug is.
The example BODY for POST to create a new SOD doesn't work. It gives an error about the "id" being in the wrong format. To get this to work the "id" should not be present at all in the BODY.
**To Reproduce** Steps to reproduce the behavior:

1. Copy POST body from sod_policy default example
2. Go to postman and try to create a sod_policy and paste the body copied from the example.
3. See error `{
    "detailCode": "400.1.3 Illegal value",
    "trackingId": "3fe4d7c80fcd4ebdb07b972c7d618e3f",
    "messages": [
        {
            "locale": "en-US",
            "localeOrigin": "DEFAULT",
            "text": "Illegal value \"0f11f2a4-7c94-4bf3-a2bd-742580fe3bde\" for field \"policy.id\"."
        },
        {
            "locale": "und",
            "localeOrigin": "REQUEST",
            "text": "Illegal value \"0f11f2a4-7c94-4bf3-a2bd-742580fe3bde\" for field \"policy.id\"."
        }
    ],
    "causes": []
}`

**Expected behavior** A policy would be created
**Actual behavior** The above error occurred. Id must be omitted from the body or set to 'null' to avoid this error. The example should reflect that.
**Screenshots** If applicable, add screenshots to help explain your problem.

**Operating System (please complete the following information):**

- OS: [e.g. Windows 10 19044.1889, Ubuntu 18.04, Mac OS Monterey 12.4]
- CLI Environment [e.g. Command Prompt, Powershell, Terminal]
- Version [e.g. 1.04]

**Browser (please complete the following information):**

- Browser: [e.g. Chrome, Firefox, Brave, Safari]
- Version [e.g. 1.04]

**Additional context** Add any other context about the problem here.

**Comment by colin-mckibben-sp** [comment]
Looks like this only affects the beta endpoint.  The v3 endpoint has the correct documentation.  I will get the beta fixed.

https://developer.sailpoint.com/idn/api/beta/create-sod-policy

**Comment by colin-mckibben-sp** [comment]
PR is open.  I'll report back once it is merged and published.

**Comment by colin-mckibben-sp** [comment]
This is now fixed
