### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Initiates Configuration Objects Import Job.' (import-sp-config)

### ISSUE THREAD

**Issue by olivier-jacques-sp** [sailpoint-oss/developer.sailpoint.com#219]
**Describe the bug** A clear and concise description of what the bug is.
It is not stated that source of NELM type are not supported but according to https://sailpoint.atlassian.net/browse/PLTIN-2313 we cannot use sp-config to import a NELM source. 
Should we update the page to specify this if this is really the case or should we fix the sp-config to support NELM soure? 
**To Reproduce** Steps to reproduce the behavior:

1. Import any created NELM source and import it using {{baseUrl}}/beta/sp-config/import
2. The source is not configured and from the UI / API it cannot be deleted
**Expected behavior** A clear and concise description of what you expected to happen.
The NELM source should appears in the UI fully configured and working.
**Actual behavior** A clear and concise description of what actually happens.
The source object is damaged and cannot be removed from UI (well using API)

**Operating System (please complete the following information):**
- OS: Windows 10 21H2 19044.2728

**Browser (please complete the following information):**
- Browser: Chrome
- Version  112.0.5615.87 

**Additional context** Add any other context about the problem here.
![NELM from UI](https://user-images.githubusercontent.com/76449451/232082638-3a6b2084-e138-4399-8f02-28562ab59b89.jpg)
export used for the import of the NELM source (here called "Kosovo External Accounts" with id d9eac7ada04f476188253fe550a98bd3)
[config_export_pcg-sb-20230413-beautitied.txt](https://github.com/sailpoint-oss/developer.sailpoint.com/files/11234321/config_export_pcg-sb-20230413-beautitied.txt)

**Comment by colin-mckibben-sp** [comment]
@james-haytko-sp Can you please update the SP config docs?  I confirmed with product management that NELM will not be supported, so we need to indicate in the docs that you can't backup/restore NELM sources.

**Comment by james-haytko-sp** [comment]
Thanks Olivier! It's updated now to tell users that they can't import from the NELM source: https://developer.sailpoint.com/idn/api/beta/import-sp-config
