### ISSUE TITLE
[Bug] Inconsistent Schema for listing users in IdentityIQ (get-users)

### ISSUE THREAD

**Issue by aaronreidsmith** [sailpoint-oss/developer.sailpoint.com#222]
**Describe the bug**

Schema descriptions do not match the examples for the `get-users` documentation of IdentityIQ

**To Reproduce** Steps to reproduce the behavior:

1. Go to `https://developer.sailpoint.com/iiq/api/get-users`
2. Click on `Example (from schema)`
3. The following fields don't match what is described on the `schema` tab:
    - `totalResults` - `schema` tab says this should be an `integer` but the example shows `"18,"`
    - `Resources.emails.primary` - `schema` tab says this should be a `boolean` but the example shows `"true"`
    - `Resources.urn:ietf:params:scim:schemas:sailpoint:1.0:User.capabilities` - `schema` tab says this should be a `string[]` but the example shows `[\"SystemAdministrator\"]`

**Expected behavior**
I expected the above fields to appear the following way in JSON (where `...` represents irrelevant/omitted fields):

```json
{
  "totalResults": 18,
  ...,
  "Resources": [
    ...,
    "emails": [
      {
        ...,
        "primary": true
      }
    ],
    "urn:ietf:params:scim:schemas:sailpoint:1.0:User": {
      ...,
      "capabilities": ["SystemAdministrator"]
    }
  ]
}
```

Alternatively I would expect the `schema` tab to be updated to match the example (if the example is correct).

**Actual behavior**

Example shows this (where `...` represents irrelevant/omitted fields):

```json
{
  "totalResults": "18,"
  ...,
  "Resources": [
    ...,
    "emails": [
      {
        ...,
        "primary": "true"
      }
    ],
    "urn:ietf:params:scim:schemas:sailpoint:1.0:User": {
      ...,
      "capabilities": "[\"SystemAdministrator\"]"
    }
  ]
}
```

**Screenshots**

`Schema` tab:

![Screenshot 2023-04-18 at 11 34 16 AM](https://user-images.githubusercontent.com/21350310/232844718-9380d6d5-86d3-4de9-bfaa-e5ef476cc0bb.png)

![Screenshot 2023-04-18 at 11 34 31 AM](https://user-images.githubusercontent.com/21350310/232844719-e1470d9d-753b-4ded-8770-f0be3072bc7e.png)

![Screenshot 2023-04-18 at 11 34 38 AM](https://user-images.githubusercontent.com/21350310/232844725-c08ec30a-558e-4929-904c-8b57b854399e.png)

`Example (from schema)` tab:

![Screenshot 2023-04-18 at 11 33 56 AM](https://user-images.githubusercontent.com/21350310/232844841-73986214-b3a1-4295-ac45-d0b2c2bef8ab.png)

![Screenshot 2023-04-18 at 11 34 03 AM](https://user-images.githubusercontent.com/21350310/232844844-3e399253-1583-454d-bffe-40f0fc7ad4f2.png)

![Screenshot 2023-04-18 at 11 34 10 AM](https://user-images.githubusercontent.com/21350310/232844849-3187e07e-1d3f-4ab5-a69c-0cf4f49cd33c.png)

**Operating System (please complete the following information):**

- OS: macOS Ventura 13.2.1
- CLI Environment: N/A
- Version: N/A

**Browser (please complete the following information):**

- Browser: Brave Browser
- Version: 1.50.119 Chromium: 112.0.5615.121 (Official Build) (arm64)

**Additional context**

N/A

**Comment by colin-mckibben-sp** [comment]
Thank you for reporting this @aaronreidsmith .  I have notified the team that owns the IIQ spec, and I will report back here once the issue is resolved.  For my reference, the ticket is IIQDOCS-544.

**Comment by jordan-violet-sp** [comment]
Slated for 8.5 release of IIQ. Please resubmit if this is still an issue after that release.

**Comment by jordan-violet-sp** [comment]
Slated for 8.5 release of IIQ. Please resubmit if this is still an issue after that release.
