### ISSUE TITLE
[Feature] Add missing classes to the IDN Rule javadocs

### ISSUE THREAD

**Issue by drosenbauer** [sailpoint-oss/developer.sailpoint.com#240]
There are a number of other missing classes that are referenced in the newly published docs:

Under Application, there are methods that return Schema, AttributeDefinition, ProvisioningConfig, ObjectConfig, and Rule. There are other methods that take a Template.Usage.

Under ProvisioningPlan, there’s a reference to ProvisioningTarget and Message.

Under ProvisioningResult, there’s a reference to ResourceObject and Message.

Under Endpoint, there is sailpoint.object.Attributes. (Also, all of the “get” methods return void?)

Under Field, there is DynamicValue and Script.

---- 

Please include these or remove references to them.

**Comment by tyler-mairose-sp** [comment]
Hello @drosenbauer,

Thank you for the list of these classes!

I took a look and resolved each of them.

Under Application, Schema and AttributeDefinition have been added. ProvisioningConfig, ObjectConfig, Rule and Template.Usage have been removed as they are not used in Rules.

Under Provisioning Plan, Message has been added. Methods referencing ProvisioningTarget have been removed as they are not used.

Under ProvisioningResult, ResourceObject and Message have been added.

Under Field, DynamicValue and Script have both been removed as they are not need for rules.

I *just* pushed the change to add sailpoint.tools.Message so it may take a few minutes to show up on developer.sailpoint.com.

Thank you again for helping make our documentation better!
