### ISSUE TITLE
[Feature] Document sailpoint.object.Identity

### ISSUE THREAD

**Issue by tyler-mairose-sp** [sailpoint-oss/developer.sailpoint.com#241]
In the Java Docs at https://developer.sailpoint.com/idn/docs/rules/java-docs, `sailpoint.object.Identity` is actually the class for `sailpoint.rule.Identity`.

We need to switch this and document `sailpoint.object.Identity` with the correct methods.

**Comment by jordan-violet-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community Forum**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/rule-java-docs-now-available-on-the-sailpoint-developer-community/10787/17

**Comment by tyler-mairose-sp** [comment]
The sailpoint.object.Identity class has been documented and sailpoint.rule.Identity has been moved to its correct path. https://github.com/sailpoint-oss/developer.sailpoint.com/commit/bacc8e86bf823d14cca7c20b58957e77a980eb4b
