### ISSUE TITLE
[Bug] Requesting changes to 'Set Identity's Password' (set-password)

### ISSUE THREAD

**Issue by calebstromgren** [sailpoint-oss/developer.sailpoint.com#242]
Step 2 on https://developer.sailpoint.com/idn/api/v3/set-password/ that says "Choose an account from the previous response that you will provide as an accountName in your request to set an encrypted password." is incorrect.  The example body contains accountId and not accountName.  In my testing this was confirmed, accountId is expected.

**Comment by james-haytko-sp** [comment]
The page is updated: https://developer.sailpoint.com/idn/api/v3/set-password/

It now says `accountId`, not `accountName`.
