### ISSUE TITLE
[Bug] Requesting changes to GET 'Accounts List' (list-accounts)

### ISSUE THREAD

**Issue by antonypetson** [sailpoint-oss/developer.sailpoint.com#266]
**Describe the bug:** Incomplete response is being returned while calling `GET {{baseUrl}}/v3/accounts?limit=10&count=true` with filters on `SourceId in ("s1","s2","s3")`.

**To Reproduce** Steps to reproduce the behaviour:

`GET {{baseUrl}}/v3/accounts?limit=10&count=true` for sourceIds which contain more than 20000 accounts (my use case)

**Expected behavior** Actual accounts available (X-Total-Count)

**Actual behavior**  Many accounts are missing and returns a reduced list

**Additional context** Add any other context about the problem here.
If I try to pull individually per source, I am getting the correct response.

**Comment by jason545454** [comment]
Maybe related, I had similar issue with GET /v3/certifications  - even though X-Total-Count was ~300, and pagination should have returned 250, it was returning 246. 

There is something funny going on with how the SailPoint API gets results from backend, in my opinion.

**Comment by colin-mckibben-sp** [comment]
@antonypetson This is a bug with the API and not a documentation issue, so I will close this issue.  Can you please submit a support ticket with the details you shared here so support can investigate and fix it?
