### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Submit an Access Request' (create-access-request)

### ISSUE THREAD

**Issue by calebstromgren** [sailpoint-oss/developer.sailpoint.com#282]
Under GRANT_ACCESS documentation there is a bullet that states 

"Supports self request and request on behalf of other users, see '/beta/access-request-config' endpoint for request configuration options."

There is now a V3 endpoint for the access request config, and the endpoints are /v3/get-access-request-config and /v3/update-access-request-config

There isn't a access-request-config in either V3 or Beta

**Comment by james-haytko-sp** [comment]
This issue has been resolved: https://developer.sailpoint.com/idn/api/v3/create-access-request
