### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Initiates Configuration Objects Export Job.' (export-sp-config)

### ISSUE THREAD

**Issue by chadcarlton** [sailpoint-oss/developer.sailpoint.com#283]
Please list the object options that are possible.

is it excludednames? or excludeNames?  etc.

**Comment by colin-mckibben-sp** [comment]
Hi @chadcarlton .  Can you please be more specific?  Links to docs and screenshots will better help us understand where the issue is.

**Comment by chadcarlton** [comment]
This can be closed, as we ended up doing something differently, but it was unclear to me at the time, if there was a way to do included Types = access Profile 
and then an exclusion in the object types.. 

Something akin to include everything except these AP ID's.....
