### ISSUE TITLE
[Bug] NERM API Docs have incorrect URLs

### ISSUE THREAD

**Issue by zachary-tarantinowoolson-sp** [sailpoint-oss/developer.sailpoint.com#304]
**Describe the bug** 
I haven't explicitly checked every endpoint/example, but the URL provided in the API call examples show as "https://developer.sailpoint.com/profiles" when the correct URL should have the endpoint preceded with "/api/" like so: "https://developer.sailpoint.com/api/profiles"

This has lead to a bit of confusion on how to utilize the NERM API as the provided examples lead to 404 errors.

**Operating System (please complete the following information):**
- OS: Windows 11 Pro 22000.2057

**Browser (please complete the following information):**
- Browser: Microsoft Edge Version 114.0.1823.79

**Comment by colin-mckibben-sp** [comment]
@zachary-tarantinowoolson-sp can you provide links to specific endpoints and screenshots showing the issue?

**Comment by zachary-tarantinowoolson-sp** [comment]
@colin-mckibben-sp 

Two examples:

POST Profile example: 
https://developer.sailpoint.com/nerm/api/post-profile
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/106765914/fbbe4f01-f9f4-4bd0-af29-0ac863b95bda)

GET workflow_sessions example:
https://developer.sailpoint.com/nerm/api/get-workflow-sessions
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/106765914/567e0640-35d7-4de2-b736-2969c16dda19)

I checked through more of the endpoints and it looks like most if not all of the examples do not have the "/api" in the request URL

**Comment by darrell-thobe-sp** [comment]
This was solved in https://github.com/sailpoint-oss/api-specs/commit/62a3d42ec70b8c075e75cb3c58fde994561870ac#diff-bcd11c2bbbe5251a370d160eeb7e2e66ffbff15474493fcae803389a702e5f96R10. If you feel there is still an issue please re-open.
