### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Get a Work Item' (get-work-item)

### ISSUE THREAD

**Issue by patrice-adp** [sailpoint-oss/developer.sailpoint.com#315]
**Describe the bug** A clear and concise description of what the bug is.
The documentation is wrong for the list of approvaltems attributes.
The fields with name "attributeXxx" are wrong, there is no prefix 'attribute' for this fields, the correct names are "operation" / "name" / "value"

**To Reproduce** Steps to reproduce the behavior:

Just do a GET and you'll see that the json output is not the same as what is described in the documentation

**Expected behavior** A clear and concise description of what you expected to happen.

Have the documentation with name that are the expected ones

**Comment by colin-mckibben-sp** [comment]
@patrice-adp can you share screenshots and a direct link to the API endpoint in question?

**Comment by patrice-adp** [comment]
Screenshot of documentation on sailoint
![work_item](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/129203619/72918d5f-c5ae-42c3-91e9-b9b4f5913bab)
Screenshot of call using postman collection
![work_item_json](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/129203619/ca1f0942-5ec0-47a7-9ed1-f413cf4c568e)

**Comment by james-haytko-sp** [comment]
This issue has been resolved: https://developer.sailpoint.com/idn/api/v3/list-work-items
