### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Create a Role' (create-role)

### ISSUE THREAD

**Issue by edwin-grimminck-sp** [sailpoint-oss/developer.sailpoint.com#318]
Documentation bug. 
The documentation still mentions a soft limit of 800 roles. This is very old in my opinion as we can currently support over 30.000 roles in IDN.

**To Reproduce** Simply go to the V3 API for Create Role.
<img width="839" alt="image" src="https://github.com/sailpoint-oss/developer.sailpoint.com/assets/18280116/c305461b-83f5-4be6-a47a-53b45c95e268">

**Comment by james-haytko-sp** [comment]
This issue has been resolved: https://developer.sailpoint.com/idn/api/v3/create-role
