### ISSUE TITLE
[Bug] Wording change - Requesting changes to 'Submit an Access Request' (create-access-request)

### ISSUE THREAD

**Issue by jason545454** [sailpoint-oss/developer.sailpoint.com#337]
Hello, 

The wording on https://developer.sailpoint.com/idn/api/beta/create-access-request/  under REVOKE_ACCESS is very hard to interpret / understand the part below in **bold**

Current wording:

- [Roles, Access Profiles] removeDate can be specified if access don't have a sunset date **or if a revoke access with a removeDate earlier than the current endDate.**

What _I think_ it means is that

- removeDate can be specified if the access doesn't already have a sunset date
- removeDate must be a future date (or does current endDate refer to identity end date??)

It should also be noted that removeDate must be in UTC timezone, not local timezone

**Comment by james-haytko-sp** [comment]
Thanks for the improvement! The documentation has been updated: https://developer.sailpoint.com/idn/api/v3/create-access-request
