### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Initiates configuration objects export job' (export-sp-config)

### ISSUE THREAD

**Issue by wyssaj** [sailpoint-oss/developer.sailpoint.com#348]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'https://developer.sailpoint.com/idn/api/beta/get-sp-config-export'
2. Observe includeTypes and excludeTypes and notice 'WORKFLOWS'
3. Submit SP-CONFIG export job including item 'WORKFLOWS' in Postman
4. Error: '"message": "java.lang.IllegalArgumentException: Supplied types are not supported: [WORKFLOWS]"'

Correct spelling in the API is 'WORKFLOW'.

- OS: [e.g. Windows 11]
- CLI Environment [N/A Error observed in Postman]
- Version [v10.17.4]

**Browser (please complete the following information):**

- Browser: [MS Edge]
- Version [116]

**Additional context** There is a spelling error in the documentation on the linked page.  It should be 'WORKFLOW' and not 'WORKFLOWS'

**Comment by colin-mckibben-sp** [comment]
Thanks for reporting this @wyssaj .  We will get this fixed internally and complete this issue once the PR is staged.

**Comment by colin-mckibben-sp** [comment]
Internal PR is staged.  Closing this as complete.
