### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'List Governance Groups' (list-workgroups)

### ISSUE THREAD

**Issue by maanxester** [sailpoint-oss/developer.sailpoint.com#349]
**Describe the bug** A clear and concise description of what the bug is.

It is possible to use the "filters" parameter within the endpoint. However, it is not included in the documentation.

**To Reproduce** Steps to reproduce the behavior:

https://{{name}}.api.identitynow.com/beta/workgroups?filters=name eq "xpto"

**Expected behavior** A clear and concise description of what you expected to happen.

**Actual behavior** A clear and concise description of what actually happens.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Operating System (please complete the following information):**

- OS: [e.g. Windows 10 19044.1889, Ubuntu 18.04, Mac OS Monterey 12.4]
- CLI Environment [e.g. Command Prompt, Powershell, Terminal]
- Version [e.g. 1.04]

**Browser (please complete the following information):**

- Browser: [e.g. Chrome, Firefox, Brave, Safari]
- Version [e.g. 1.04]

**Additional context** Add any other context about the problem here.

**Comment by jordan-violet-sp** [comment]
Currently being worked on in https://github.com/sailpoint-oss/api-schema-validator/issues/6
