### ISSUE TITLE
[Bug] Create a campaign (create-campaign): incorrect possible values for reviewer type

### ISSUE THREAD

**Issue by rob-buskens-sp** [sailpoint-oss/developer.sailpoint.com#365]
**Describe the bug** A clear and concise description of what the bug is.
On this page: [create-campaign](https://developer.sailpoint.com/idn/api/v3/create-campaign) under searchCampaignInfo/reviewer/type

it says the possible DTO types are IDENTITY and GOVERNANCE_GROUP, however then under possible values lists ACCOUNT_CORRELATION_CONFIG, ACCESS_PROFILE, ACCESS_REQUEST_APPROVAL, ACCOUNT, APPLICATION, CAMPAIGN, CAMPAIGN_FILTER, CERTIFICATION, CLUSTER, CONNECTOR_SCHEMA, ENTITLEMENT, GOVERNANCE_GROUP, IDENTITY, IDENTITY_PROFILE, IDENTITY_REQUEST, LIFECYCLE_STATE, PASSWORD_POLICY, ROLE, RULE, SOD_POLICY, SOURCE, TAG, TAG_CATEGORY, TASK_RESULT, REPORT_RESULT, SOD_VIOLATION, ACCOUNT_ACTIVITY, WORKGROUP

**To Reproduce** Steps to reproduce the behavior:

1. as above

**Expected behavior** A clear and concise description of what you expected to happen.
This list matches the applicable dto types

**Actual behavior** A clear and concise description of what actually happens.
See screen shot

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screenshot 2023-09-29 at 11 54 59 AM](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/105882429/093b020b-a60b-4e92-80a9-46653f9a313b)

**Operating System (please complete the following information):**

- OS: n/a
- CLI Environment:  n/a
- Version: n/a

**Browser (please complete the following information):**

- Browser: Chrome
- Version: 117.0.5938.92 (Official Build) (arm64)

**Additional context** Add any other context about the problem here.

**Comment by tyler-mairose-sp** [comment]
@rob-buskens-sp This was fixed when DEVREL-1185 was merged in. See https://github.com/sailpoint-oss/developer.sailpoint.com/commit/d31c413a11dbd91e2dc0e719dbad10a0ec16b536

As Jordan mentioned a lot of DTO objects were fixed as a result of this. We can thank @james-haytko-sp for that one!
