### ISSUE TITLE
[Bug] Undocumented identityState in 'Retrieves Lifecycle State' (get-lifecycle-state)

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/developer.sailpoint.com#409]
**Describe the bug** 
When retrieving a Lifecycle State, an `identityState` - which seems always null - is returned.
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/82362286/a72553da-82da-444d-863d-c84f1fc91207)

However, this property is missing from the spec:
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/82362286/6ff7de31-4033-423b-8936-1154ab3c083b)

**To Reproduce** Steps to reproduce the behavior:

1. Retrieve a Lifecycle State
2. Look for the `identityState` property

**Comment by philip-ellis-sp** [comment]
DEVREL-1410
