### ISSUE TITLE
[Bug] ReadOnly properties in the spec do not show up on the developer site. 

### ISSUE THREAD

**Issue by tyler-mairose-sp** [sailpoint-oss/developer.sailpoint.com#411]
**Describe the bug**

When the api specifications have read only attributes, they do not show on the docusarus site.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://developer.sailpoint.com/idn/api/beta/list-workgroups and see that `memberCount` and `connectionCount` are missing.
2. Go to https://github.com/sailpoint-oss/api-specs/blob/main/idn/beta/schemas/workgroups/WorkgroupDto.yaml and see the properties are defined as readonly.

**Expected behavior** A clear and concise description of what you expected to happen.

I would expect to see these attributes show up as part of the response schema even if they are read only.

**Comment by philip-ellis-sp** [comment]
closing as these are now visible
