### ISSUE TITLE
[Bug] Requesting changes to 'Get a Role' (get-role)

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/developer.sailpoint.com#413]
**Describe the bug** 

`approvalSchemes`'s `revocationRequestConfig` for roles is the same as for access profile whereas `approvalSchemes`'s `accessRequestConfig` is different.

cf. https://developer.sailpoint.com/idn/api/v3/get-role :

![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/82362286/d139a70b-331d-4ca1-b699-13e33ee70feb)

**Expected behavior** 

 `approvalSchemes`'s `revocationRequestConfig` for roles should not allow APP_OWNER or  SOURCE_OWNER.
As for `approvalSchemes`'s `accessRequestConfig`, only OWNER, MANAGER, GOVERNANCE_GROUP should be allowed.

**Comment by philip-ellis-sp** [comment]
Closing as these updates have been made
