### ISSUE TITLE
[Bug] Requesting changes to 'Check connection for source connector.' (test-source-connection)

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/developer.sailpoint.com#421]
**Describe the bug** 

No schema is presented for a 200:
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/82362286/4bc4094e-3bdd-4656-ab93-da2e5257d6b7)

An example is provided based on a schema but for a success.
What is expected for an error?

**Comment by philip-ellis-sp** [comment]
Closing as error types are now also available in the spec
