### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Auth User Details' (get-auth-user)

### ISSUE THREAD

**Issue by kjakubiak** [sailpoint-oss/developer.sailpoint.com#438]
**Describe the bug** A clear and concise description of what the bug is.
This endpoint works fine as long as you use PAT token to authenticate, if you use Global API Token it fails with 403. 
**To Reproduce** Steps to reproduce the behavior:

![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/37939333/6e4005c3-effd-4ccc-980e-7daa9bb182c3)

Would be good to add this information to the documentation or to report this as a bug to the development team.

**Comment by philip-ellis-sp** [comment]
Closing as the API specifically states that it requires a user based API Token to work: https://developer.sailpoint.com/idn/api/v3/identitynow-v-3-api#authentication
