### ISSUE TITLE
[Feature] Cloud Rule pages (such as Manager Correlation) should describe how to use the rules, not just how to code one.

### ISSUE THREAD

**Issue by stephen-holinaty-sp** [sailpoint-oss/developer.sailpoint.com#453]
**Is your feature request related to a problem? Please describe.** 
ManagerCorrelation rules are immensely valuable, however the Rule page only shows how to write a rule.
it does not have reference to how to tie it to the managerCorrelationRule field on a source
it does not show what has to be done within the tenant to utilize the rule

**Describe the solution you'd like.** A clear and concise description of what to do and where to do it, end to end, to utilize a cloud rule for its intended purpose

**Comment by philip-ellis-sp** [comment]
Hi Stephen, I am closing this issue as we have plans to improve the documentation around rules, but this particular issue is something that is difficult to track and understand when it is "complete". In the meantime, if you have a solid implementation of manager correlation that you could share publicly, I think we would like to be able to add that to the documentation.
