### ISSUE TITLE
Update SaaS Connectivity "Connector Commands" docs with connector-spec commands

### ISSUE THREAD

**Issue by hari-patel-sp** [sailpoint-oss/developer.sailpoint.com#472]
Our current Connector Commands documentation for SaaS connectors (https://developer.sailpoint.com/idn/docs/saas-connectivity/connector-commands) only lists the human-friendly command names for the `commands` array that the connector-spec.json file contains. For example, we show that "Test Connection" is supported, but the value you must specify in the `commands` array is `std:test-connection`:

`"commands": [
        "std:test-connection",
        "std:account:list",
        "std:account:read",
        "std:entitlement:list",
        "std:entitlement:read",
        "std:account:update",
        "std:account:create",
        "std:account:enable",
        "std:account:disable"
 ],`

Nowhere in our online documentation was I able to find the corresponding command value for all of our supported connector commands - I had to navigate through several SaaS connectors built by SailPoint Engineering in order to find the commands I was looking for.

One possible solution here would be to provide the system name next to the human-friendly name on the "cards" of the below page:
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/44035796/f6305bf8-207f-436e-a81b-0ea1443e49ea)

Additionally, an explicit callout for the value which should be included in your connector-spec.json file if you want to support that particular command. E.g., on the Account Create details page (https://developer.sailpoint.com/idn/docs/saas-connectivity/commands/account-create), state somewhere that you must provide `std:account:create` in the `commands` array.

**Comment by darrell-thobe-sp** [comment]
Thank you for the feedback @hari-patel-sp this was resolved with the following [commit ](https://github.com/sailpoint-oss/developer.sailpoint.com/commit/0fcd8f977922522386d80684c1dfc7ea3120f21a)
