### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Get the status of a bulk job' (get-job-status)

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/developer.sailpoint.com#484]
**Describe the bug**

The "generated code" in any language is not mentioning the *required* `job_id` parameter.
Example in curl:
![image](https://github.com/sailpoint-oss/developer.sailpoint.com/assets/82362286/e0e41a4b-cc5d-4fa6-836e-ae5891e29f99)

**To Reproduce**

1. Go to https://developer.sailpoint.com/nerm/api/get-profile/
2. For any language, the required query parameter is not used

**Expected behavior** 

For curl for instance, something like 
```
curl -L -X GET 'https://acmeco.nonemployee.com/api/job_status?job_id=:job_id' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>'
```

**_There might be other places where required query parameters are not used in the code examples._**

**Comment by tyler-mairose-sp** [comment]
Hey @yannick-beot-sp,

If you fill out the required parameter in the section just below the code examples it will update the code.

<img width="594" alt="image" src="https://github.com/sailpoint-oss/developer.sailpoint.com/assets/84410962/fd61288f-81d3-49f1-9090-2fca121d84d5">

**Comment by yannick-beot-sp** [comment]
I see.
A few remarks on that:
1. In "light" theme, the input box is not very clear/visible. It looks like the description of the parameter. There is probably not enough contrast between the background of the box and the background of the input, without border or else.
![image](https://github.com/user-attachments/assets/72462bb0-6058-4cd0-aae4-85e34d2a25af)

2. If you look at https://developer.sailpoint.com/docs/api/nerm/v1/get-profile-type, the generated code is:
```
curl -L -X GET 'https://acmeco.nonemployee.com/api/profile_types/:id' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer <TOKEN>'
````
![image](https://github.com/user-attachments/assets/ca2f8363-72ed-489c-bc4c-8325c6457545)
Which makes more sense to me

3. As this is a required parameter, could me not put some default value, coming from the example of the API spec or something, so we ensure that this parameter is seen/visible/present in the code?
