### ISSUE TITLE
[Bug] text doesn't wrap on long titles for community cards on the homepage

### ISSUE THREAD

**Issue by jordan-violet-sp** [sailpoint-oss/developer.sailpoint.com#63]
**Describe the bug**
When the community cards pull in topic titles with long words (in this case, a long variable), it doesn't wrap and spills off the card.

**To Reproduce**
Not reproducible, it just depends on if the homepage happens to dynamically pull in a topic title with a long word/variable.

**Expected behavior**
It should either wrap, or the word should be forcibly shortened.

**Screenshots**
![image](https://user-images.githubusercontent.com/69053702/193074620-615ef778-dd77-42d5-a6e6-525f5e4ff8af.png)

**Operating System (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox 

**Additional context**
No additional context.

**Comment by luke-hagar-sp** [comment]
You want something like break-all, overflow-hidden, or overflow-ellipsis.
I mainly use tailwind so apologies for the short hand.
