### ISSUE TITLE
[Feature] Ability to download the OpenAPI spec

### ISSUE THREAD

**Issue by jordan-violet-sp** [sailpoint-oss/developer.sailpoint.com#64]
**Is your feature request related to a problem? Please describe.**
I used to be able to download the spec directly from the API documentation, and would like to be able to do that again.

**Describe the solution you'd like.**
I'd like to have the option to download the API spec directly to use for my own purposes.

**Describe alternatives you've considered.**
No other considerations are available if I am unable to download the spec directly. It would be nice if we also auto-generated other tools, like Postman collections and SDKs so those wouldn't have to be built manually.

**Additional context**
No additional context.

**Comment by jordan-violet-sp** [comment]
Submitted an issue to PaloAltoNetworks/docusaurus-openapi-docs: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/348

**Comment by sserrata** [comment]
Hi @jordan-violet-sp, the `downloadUrl` option is already available in the plugin. It works by specifying a URL link to the spec, although in some cases you may need to "pre-bundle" your spec so it's available in a single file.

I believe your feature request is asking for the ability to reference an OpenAPI specification by file path such that it can be bundled and provided as a download URL. Although technically feasible, I am not sure if and how Docusaurus/webpack could support this.
