### ISSUE TITLE
[Bug] Character encoding issues

### ISSUE THREAD

**Issue by luke-hagar-sp** [sailpoint-oss/developer.sailpoint.com#71]
**Describe the bug** A clear and concise description of what the bug is.
Some characters are not being encoded or parsed correctly in the API documentation

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://developer.sailpoint.com/idn/api/beta/certification-campaigns
2. Scroll down to the section pictured

**Expected behavior** A clear and concise description of what you expected to
happen.

**Actual behavior** A clear and concise description of what actually happens.

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screen Shot 2022-10-03 at 11 14 39 AM](https://user-images.githubusercontent.com/98849695/193627799-c07ae846-ac2c-469a-a988-8245518f1795.png)

Operating System (please complete the following information):

Browser: Vivaldi 5.4.2753.51 (Stable channel) (arm64)
OS: MacOS Monterey 12.6
CLI Environment NA

**Additional context** Add any other context about the problem here.

**Comment by luke-hagar-sp** [comment]
from what I can tell, It looks like this can be traced all the way here:
https://github.com/facebook/docusaurus/blob/6c8af03f513891c7ff6ab049480e274cc12d119a/packages/docusaurus/src/client/exports/Translate.tsx#L33

Path I followed is:
1. products/idn/api/beta/sidebar.js 
```js
import DocCardList from '@theme/DocCardList';
import {useCurrentSidebarCategory} from '@docusaurus/theme-common';

<DocCardList items={useCurrentSidebarCategory().items}/>
```

2. https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/DocCardList/index.tsx
```js
<DocCard item={item} />
```

3. https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/DocCard/index.tsx
```js
description={translate(
        {
          message: '{count} items',
          id: 'theme.docs.DocCard.categoryDescription',
          description:
            'The default description for a category card in the generated index about how many items this category includes',
        },
```

but I could have missed something in between.

**Comment by jordan-violet-sp** [comment]
Fixed in a previous pull request.
