### ISSUE TITLE
[Feature] Response schema buttons don't properly utilize the space, requiring scrolling

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#72]
**Is your feature request related to a problem? Please describe.**

The response schema buttons at the bottom of each endpoint only show 4 at a time, requiring scrolling to see the other response codes.  Most monitors should be able to display all of the response codes.

![image](https://user-images.githubusercontent.com/75683148/194091133-07882c00-fc95-4039-a8ab-794fbc899843.png)

**Describe the solution you'd like.**

Expand the response schema selection so scrolling isn't required unless the screen is shrunk or on a mobile device.

**Describe alternatives you've considered.**

The only alternative is to scroll.

**Comment by jayeshuk** [comment]
Interested to work on this issue

**Comment by darrell-thobe-sp** [comment]
This is fixed with commit 86910623cab4f6318544ea7ec0bbc56ec1312a1a
