### ISSUE TITLE
[Bug] Unable to render "allOf" schema

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#73]
**Describe the bug** 

Schema’s that use the “allOf” keyword are not properly rendered.

**To Reproduce** 

See the response schema for this endpoint: https://developer.sailpoint.com/idn/api/v3/list-identity-profiles

**Expected behavior** 

The schema should render all of the properties that are included in an "allOf" schema.

**Actual behavior** 

The schema simply displays "allOf" instead of rendering the properties.

**Screenshots** 

![image](https://user-images.githubusercontent.com/75683148/194091850-60d44c24-218a-4486-b44c-a414d57f8ae6.png)

**Operating System (please complete the following information):**

- OS: Mac OS

**Browser (please complete the following information):**

- Browser: Chrome
- Version: 106.0.5249.91

**Comment by jordan-violet-sp** [comment]
@philip-ellis-sp can we talk to the pan.dev team about the plugin supporting this feature?

**Comment by philip-ellis-sp** [comment]
Submitted an issue for this bug: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/349
