### ISSUE TITLE
[Bug] Examples (from schema) don't use the provided examples in the spec

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#74]
**Describe the bug**

The GET /v3/identity-profiles schema provides examples for each of the properties, but the plugin will not use those examples.  Instead, it provides default examples based on the data type.
![image](https://user-images.githubusercontent.com/75683148/194092653-56b1f784-76be-439b-acf5-5f93aaa75eac.png)

Interestingly, the request body schemas do use the examples provided in the spec…
![image](https://user-images.githubusercontent.com/75683148/194092690-a7e36596-b3cf-4811-b378-84c3612cfd50.png)

**To Reproduce** Steps to reproduce the behavior:

See the "Example (from schema)" for this endpoint. https://developer.sailpoint.com/idn/api/v3/list-identity-profiles

**Expected behavior** 

If the API spec provides examples for each property in a schema, then the "Examples (from schema)" should use those examples.

**Actual behavior** 

The "Examples (from schema)" uses a default value appropriate for each data type in the schema, which is not very helpful.

**Operating System (please complete the following information):**

- OS: Mac OS

**Browser (please complete the following information):**

- Browser: Chrome
- Version 106.0.5249.91

**Comment by jordan-violet-sp** [comment]
Fixed in a previous PR.
