### ISSUE TITLE
[Bug] API docs not displaying multiple examples for request body

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#75]
**Describe the bug** 

Some endpoints, like the search endpoint, have multiple request body examples in the spec.  However, the plugin only displays one example.

![image](https://user-images.githubusercontent.com/75683148/194093593-69d7408f-8c7d-4067-ad85-ffca59d46d21.png)

**To Reproduce** Steps to reproduce the behavior:

See the search endpoint request body examples, which only shows one example.  There are more defined in the spec.
https://developer.sailpoint.com/idn/api/v3/search-post

**Expected behavior** 

The API docs should all defined examples for each request body when applicable.

**Actual behavior**

The API docs only show one example for request bodies that have more than one defined in the spec.

**Operating System (please complete the following information):**

- OS: Mac OS

**Browser (please complete the following information):**

- Browser: Chrome
- Version 106.0.5249.91

**Comment by philip-ellis-sp** [comment]
Fixed in a previous PR
