### ISSUE TITLE
[Bug] PATCH /v3/accounts not displaying example request body

### ISSUE THREAD

**Issue by colin-mckibben-sp** [sailpoint-oss/developer.sailpoint.com#76]
**Describe the bug**

The endpoint doc for https://developer.sailpoint.com/idn/api/v3/update-account isn't using the example provided in the spec.

![image](https://user-images.githubusercontent.com/75683148/194094621-a9fe40b3-31f8-4a24-a402-fd6c992e011c.png)

**To Reproduce** Steps to reproduce the behavior:

See this endpoint: https://developer.sailpoint.com/idn/api/v3/update-account isn't using the example provided in the spec.

**Expected behavior** 

This endpoint has an example defined that should be rendered in the doc.

**Actual behavior** 

The endpoint doc is not rendering the example, and just showing an empty array.

**Operating System (please complete the following information):**

- OS: Mac OS

**Browser (please complete the following information):**

- Browser: Chrome
- Version 106.0.5249.91

**Additional context** Add any other context about the problem here.

**Comment by jordan-violet-sp** [comment]
Fixed.
