### ISSUE TITLE
[Bug] Update required fields for 'Create an Identity Profile' (create-identity-profile)

### ISSUE THREAD

**Issue by paul-davis-sp** [sailpoint-oss/developer.sailpoint.com#84]
**Describe the bug** A clear and concise description of what the bug is.

The documentation says only `name` field is required to create an identity profile, but you must also provide `authoritativeSource`.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://developer.sailpoint.com/idn/api/beta/create-identity-profile
2. Notice that only the name field in the request body is marked required, but if you try to submit this request without authoritativeSource object, you will get 400 error (which is correct behavior, the docs are just wrong)

**Expected behavior** A clear and concise description of what you expected to
happen.

Expected that the `authoritativeSource` field is also marked as required.

**Actual behavior** A clear and concise description of what actually happens.

`authoritativeSource` is not marked required

**Screenshots** If applicable, add screenshots to help explain your problem.
![Screen Shot 2022-10-11 at 2 06 11 PM](https://user-images.githubusercontent.com/39532127/195364959-124c0fbb-5092-4199-8568-87a4cb65a01e.png)

**Comment by colin-mckibben-sp** [comment]
This has been fixed as part of a previous deployment.
