### ISSUE TITLE
[Bug] Your Bug Report Here Requesting changes to 'Password Management'

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/developer.sailpoint.com#85]
HTML entities in the page description. 
`&39;` should be replaced by the corresponding character.
This issue may be present in other pages.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://developer.sailpoint.com/idn/api/beta/password-management/

**Screenshots** 
![image](https://user-images.githubusercontent.com/82362286/195794166-47c86b76-71fb-41dd-a2e3-ad29ecf29765.png)

**Comment by jordan-violet-sp** [comment]
Fixed in a previous PR.
